"""
SQLAlchemy ORM models for TrafficVision AI.

Tables
------
* ``violations``    — one row per detected violation instance in an image.
* ``vehicles``      — one row per detected vehicle in an image.
* ``analytics_cache`` — pre-aggregated violation statistics for a time window.

All primary keys are UUID, timestamps use TIMESTAMPTZ (timezone-aware), and
bounding boxes are stored as JSONB for flexible querying.

Requirements: 3.1, 3.2, 3.3
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from sqlalchemy.sql import func


# ---------------------------------------------------------------------------
# Declarative base
# ---------------------------------------------------------------------------

class Base(DeclarativeBase):
    """Shared declarative base for all ORM models."""
    pass


# ---------------------------------------------------------------------------
# Helper: default UUID factory
# ---------------------------------------------------------------------------

def _uuid_factory() -> str:
    """Return a new UUID4 string; used as default for PK columns."""
    return str(uuid.uuid4())


# ---------------------------------------------------------------------------
# Vehicle model (must be defined before Violation because of the FK)
# ---------------------------------------------------------------------------

class Vehicle(Base):
    """
    Represents a single detected vehicle in one uploaded image.

    Columns
    -------
    id            : UUID primary key (generated by the application).
    image_id      : UUID of the source image (logical reference, no DB-level FK).
    vehicle_class : Detected class label, e.g. ``"motorcycle"``, ``"car"``.
    bounding_box  : JSONB dict ``{"x1": int, "y1": int, "x2": int, "y2": int}``.
    plate_number  : Optional OCR-extracted plate text (e.g. ``"MH12DE1433"``).
    created_at    : Timestamp with timezone, set to UTC now() on insert.

    Requirement: 3.2
    """

    __tablename__ = "vehicles"

    # Primary key — UUID stored as a native PostgreSQL UUID type.
    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        default=_uuid_factory,
        comment="UUID primary key",
    )

    image_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        nullable=False,
        comment="UUID of the source image (no DB-level FK constraint)",
    )

    vehicle_class: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        comment="Detected vehicle class label",
    )

    # JSONB stores {x1, y1, x2, y2} coordinates.
    bounding_box: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        comment="Bounding box coordinates as JSONB",
    )

    plate_number: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        comment="OCR-extracted plate number, nullable",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=lambda: datetime.now(timezone.utc),
        comment="Row creation timestamp (UTC)",
    )

    # Back-reference: a vehicle may have 0..* violations linked to it.
    violations: Mapped[list["Violation"]] = relationship(
        "Violation",
        back_populates="vehicle",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    # ------------------------------------------------------------------ Indexes
    __table_args__ = (
        Index("idx_vehicles_image_id", "image_id"),
    )

    def __repr__(self) -> str:
        return (
            f"<Vehicle id={self.id!r} class={self.vehicle_class!r} "
            f"image_id={self.image_id!r}>"
        )


# ---------------------------------------------------------------------------
# Violation model
# ---------------------------------------------------------------------------

class Violation(Base):
    """
    Represents a single detected traffic violation tied to one vehicle in one
    uploaded image.

    Columns
    -------
    id                   : UUID primary key.
    image_id             : UUID of the source image (no DB-level FK).
    vehicle_id           : FK → vehicles.id (SET NULL on vehicle deletion).
    violation_type       : One of the ``ViolationType`` enum values.
    confidence           : Float in [0.0, 1.0] enforced by a CHECK constraint.
    bounding_box         : JSONB dict ``{"x1": int, "y1": int, "x2": int, "y2": int}``.
    plate_number         : Optional associated plate text.
    annotated_image_path : MinIO object path for the annotated JPEG, nullable.
    created_at           : Timestamp with timezone.

    Requirement: 3.1
    """

    __tablename__ = "violations"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        default=_uuid_factory,
        comment="UUID primary key",
    )

    image_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        nullable=False,
        comment="UUID of the source image",
    )

    vehicle_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("vehicles.id", ondelete="SET NULL"),
        nullable=True,
        comment="FK to vehicles.id; SET NULL when the vehicle row is deleted",
    )

    violation_type: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        comment="Violation type label, e.g. HELMET_NON_COMPLIANCE",
    )

    confidence: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="ML model confidence in [0.0, 1.0]",
    )

    bounding_box: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        comment="Bounding box coordinates as JSONB",
    )

    plate_number: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        comment="Associated plate number, nullable",
    )

    annotated_image_path: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="MinIO object path for the annotated image; null if generation failed",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=lambda: datetime.now(timezone.utc),
        comment="Row creation timestamp (UTC)",
    )

    # Relationship to Vehicle (many violations belong to one vehicle).
    vehicle: Mapped["Vehicle | None"] = relationship(
        "Vehicle",
        back_populates="violations",
    )

    # ------------------------------------------------------------------ Constraints & Indexes
    __table_args__ = (
        # Enforce confidence is in [0.0, 1.0] at the DB level.
        CheckConstraint(
            "confidence BETWEEN 0.0 AND 1.0",
            name="chk_violations_confidence_range",
        ),
        Index("idx_violations_image_id", "image_id"),
        Index("idx_violations_type", "violation_type"),
        Index("idx_violations_created_at", "created_at", postgresql_ops={"created_at": "DESC"}),
        Index("idx_violations_plate", "plate_number"),
    )

    def __repr__(self) -> str:
        return (
            f"<Violation id={self.id!r} type={self.violation_type!r} "
            f"confidence={self.confidence!r} image_id={self.image_id!r}>"
        )


# ---------------------------------------------------------------------------
# AnalyticsCache model
# ---------------------------------------------------------------------------

class AnalyticsCache(Base):
    """
    Pre-aggregated violation counts for a specific time window and violation type.

    The cache layer lets the analytics endpoint skip expensive GROUP BY queries
    when a fresh result (≤ 5 minutes old) is already stored.

    Columns
    -------
    id             : UUID primary key.
    window_start   : Start of the aggregation window (inclusive, UTC).
    window_end     : End of the aggregation window (inclusive, UTC).
    violation_type : Violation type label the count applies to.
    count          : Pre-aggregated violation count (default 0).
    updated_at     : Timestamp of the last cache write (used for TTL check).

    A UNIQUE constraint on ``(window_start, window_end, violation_type)`` ensures
    at most one cache row exists per window-type combination.

    Requirement: 3.3
    """

    __tablename__ = "analytics_cache"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        default=_uuid_factory,
        comment="UUID primary key",
    )

    window_start: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        comment="Start of the aggregation window (UTC, inclusive)",
    )

    window_end: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        comment="End of the aggregation window (UTC, inclusive)",
    )

    violation_type: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        comment="Violation type label this count row applies to",
    )

    count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        comment="Pre-aggregated violation count",
    )

    by_date: Mapped[list[dict] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Pre-aggregated daily violation counts as JSONB",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=lambda: datetime.now(timezone.utc),
        default=lambda: datetime.now(timezone.utc),
        comment="Timestamp of last cache write (used for 5-minute TTL check)",
    )

    # ------------------------------------------------------------------ Constraints & Indexes
    __table_args__ = (
        # One cache row per window + violation type combination.
        UniqueConstraint(
            "window_start",
            "window_end",
            "violation_type",
            name="idx_analytics_window_type",
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<AnalyticsCache id={self.id!r} type={self.violation_type!r} "
            f"count={self.count!r} window=[{self.window_start!r}, {self.window_end!r}]>"
        )
